In [1]:
# run libraries
import pandas as pd
import numpy as np
from datetime import datetime # asdf

In [2]:
# read and load data files
stops = pd.read_csv("data/stops.txt")
routes = pd.read_csv("data/routes.txt")
stop_times = pd.read_csv("data/stop_times.txt")
trips = pd.read_csv("data/trips.txt")
calendar = pd.read_csv("data/calendar.txt")
calendar_dates = pd.read_csv("data/calendar_dates.txt")
shapes = pd.read_csv("data/shapes.txt")

In [3]:
# helper function to read and validate schema for each data set
def schema(dataframe):
    print(dataframe.shape, "\n\nData Types:")
    print(dataframe.dtypes, "\n\nMissing Entries:")
    print(dataframe.isnull().sum())

---

## Table of Contents
1. [**Stops**](#stops)
2. [**Routes**](#routes)
3. [**Stop Times**](#stop-times)
4. [**Trips**](#trips)
5. [**Calendar**](#calendar)
6. [**Calendar Dates**](#calendar-dates)
7. [**Shapes**](#shapes)
8. [**Foreign Key Validations**](#foreign-key-validations)
9. [**Edge List**](#edge-list)

---

## Stops

The `stops` data tells us information regarding transit stopping points across Calgary. 

Includes the following columns:
- `stop_id`: Identifies a location to stop at: stop/platform, station, entrance/exit, generic node or boarding area
- `stop_code`: Short text or a number that identifies the location for riders. These codes are often used in phone-based transit information systems or printed on signage to make it easier for riders to get information for a particular location. May be the same as `stop_id`.
- `stop_name`: Name of the location.
- `stop_desc`: Description of the location that provides useful, quality information.
- `stop_lat`: Latitude of the location.
- `stop_lon`: Longitude of the location.
- `zone_id`: Identifies the fare zone for a stop. If this record represents a station or station entrance, the `zone_id` is ignored.
- `stop_url`: URL of a web page about the location.
- `location_type`: Type of location, classifed as:
    - `0` (or empty) - **Stop** (or **Platform**). A location where passengers board or disembark from a transit vehicle.
    - `1` - **Station**. A physical structure or area that contains one or more platform.
    - `2` - **Entrance/Exit**. A location where passengers can enter or exit a station from the street.
    - `3` - **Generic Node**. A location within a station, not matching any other location_type.
    - `4` - **Boarding Area**. A specific location on a platform, where passengers can board and/or dropoff from vehicles.


*For further information, refer to the official GTFS documentation (https://gtfs.org/documentation/schedule/reference/#stopstxt).*

In [4]:
# schema and data validation
schema(stops)
stops.head()

(6173, 9)

Data Types:
stop_id            int64
stop_code          int64
stop_name         object
stop_desc        float64
stop_lat         float64
stop_lon         float64
zone_id          float64
stop_url         float64
location_type      int64
dtype: object

Missing Entries:
stop_id             0
stop_code           0
stop_name           0
stop_desc        6173
stop_lat            0
stop_lon            0
zone_id          6173
stop_url         6173
location_type       0
dtype: int64

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type
0,112112,112112,Crescent Heights High School,NaN,51.060931,-114.065158,NaN,NaN,0
1,1800,1800,EB 17 AV SE @ 84 ST SE,NaN,51.037651,-113.911093,NaN,NaN,0
2,1802,1802,NB Centre ST N @ 78 AV N nearside,NaN,51.122337,-114.071250,NaN,NaN,0
3,1803,1803,EB 46 AV SE @ Highfield CI SE,NaN,51.011541,-114.044189,NaN,NaN,0
4,1804,1804,EB 120 AV NE @ 16 ST NE,NaN,51.161538,-114.022383,NaN,NaN,0

In [5]:
# remove 'zone_id', 'stop_desc', and 'stop_url' columns since they are all empty columns and provide no useful information for later
stops = stops.drop(['stop_code', 'zone_id', 'stop_desc', 'stop_url'], axis=1)
stops

,stop_id,stop_name,stop_lat,stop_lon,location_type
0,112112,Crescent Heights High School,51.060931,-114.065158,0
1,1800,EB 17 AV SE @ 84 ST SE,51.037651,-113.911093,0
2,1802,NB Centre ST N @ 78 AV N nearside,51.122337,-114.071250,0
3,1803,EB 46 AV SE @ Highfield CI SE,51.011541,-114.044189,0
4,1804,EB 120 AV NE @ 16 ST NE,51.161538,-114.022383,0
...,...,...,...,...,...
6168,9983,WB 6 AV SW @ E. of 1 ST SW,51.047627,-114.064416,0
6169,9984,WB 6 AV SE @ 1 ST SE,51.047498,-114.060015,0
6170,9995,EB Dalhousie DR @ Dalham CR NW,51.106221,-114.158316,0
6171,9996,NB 52 ST SE @ 86 AV SE,50.976257,-113.958240,0
6172,9998,NB 19 ST SE @ 62 AV SE,50.997509,-114.013415,0

In [6]:
# helper function to check for duplicates (for id columns)
def unique_column(df, col_name):
    counts = df[col_name].value_counts()
    dupes = counts[counts > 1]
    return dupes.index.tolist()

In [7]:
# verify invalid entries
# ensure all stop_ids are unique
print("Duplicate stop_ids:", unique_column(stops, 'stop_id'))

# check for any invalid 'location_type' codes
invalid_location_type = stops[~stops['location_type'].isin([0,1,2,3,4])]['stop_id'].tolist()
print("Stops with invalid location_type:", invalid_location_type)

Duplicate stop_ids: []
Stops with invalid location_type: []

---

## Routes

The `routes` data tells us information regarding transit routes across Calgary. 

Includes the following columns:
- `route_id`: Identifies a route.
- `route_short_name`: Short name of a route. Often a short, abstract identifier (e.g., "32", "100X", "Green") that riders use to identify a route.
- `route_long_name`: Full name of a route. This name is generally more descriptive than the route_short_name and often includes the route's destination or stop.
- `route_desc`: Description of a route that provides useful, quality information.
- `route_type`: Indicates the type of transportation used on a route. These are labeled as:
    - `0` - **Tram, Streetcar, Light rail**. Any light rail or street level system within a metropolitan area.
    - `1` - **Subway, Metro**. Any underground rail system within a metropolitan area.
    - `2` - **Rail**. Used for intercity or long-distance travel.
    - `3` - **Bus**. Used for short- and long-distance bus routes.
    - `4` - **Ferry**. Used for short- and long-distance boat service.
    - `5` - **Cable Tram**. Used for street-level rail cars where the cable runs beneath the vehicle (e.g., cable car in San Francisco).
    - `6` - **Aerial lift, suspended cable car (e.g., gondola lift, aerial tramway)**. Cable transport where cabins, cars, gondolas or open chairs are suspended by means of one or more cables.
    - `7` - **Funicular**. Any rail system designed for steep inclines.
    - `11` - **Trolleybus**. Electric buses that draw power from overhead wires using poles.
    - `12` - **Monorail**. Railway in which the track consists of a single rail or a beam.
- `route_url`: URL of a web page about the particular route.
- `route_color`: Route color designation that matches public facing material. Defaults to white (`#FFFFFF`) when omitted or left empty.
- `route_text_color`: Legible color to use for text drawn against a background of route_color. Defaults to black (`#000000`) when omitted or left empty.

*For further information, refer to the official GTFS documentation (https://gtfs.org/documentation/schedule/reference/#routestxt).*

In [8]:
schema(routes)
routes.head()

(414, 8)

Data Types:
route_id             object
route_short_name     object
route_long_name      object
route_desc          float64
route_type            int64
route_url           float64
route_color         float64
route_text_color    float64
dtype: object

Missing Entries:
route_id              0
route_short_name      0
route_long_name       0
route_desc          414
route_type            0
route_url           414
route_color         414
route_text_color    414
dtype: int64

,route_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color
0,1-20781,1,Bowness/Forest Lawn,NaN,3,NaN,NaN,NaN
1,1-20789,1,Bowness/Forest Lawn,NaN,3,NaN,NaN,NaN
2,2-20781,2,Mount Pleasant/Killarney 17 Av SW,NaN,3,NaN,NaN,NaN
3,2-20789,2,Mount Pleasant/Killarney 17 Av SW,NaN,3,NaN,NaN,NaN
4,3-20781,3,Sandstone/Elbow Dr SW,NaN,3,NaN,NaN,NaN

In [9]:
# remove 'route_desc', 'route_url', 'route_color' and 'route_text_color' as they are all empty and contain no useful information
routes = routes.drop(['route_desc', 'route_url', 'route_color', 'route_text_color'], axis=1)
routes

,route_id,route_short_name,route_long_name,route_type
0,1-20781,1,Bowness/Forest Lawn,3
1,1-20789,1,Bowness/Forest Lawn,3
2,2-20781,2,Mount Pleasant/Killarney 17 Av SW,3
3,2-20789,2,Mount Pleasant/Killarney 17 Av SW,3
4,3-20781,3,Sandstone/Elbow Dr SW,3
...,...,...,...,...
409,890-20781,890,St. John Henry Newman/ Seton,3
410,892-20781,892,St. Isabella/ Mckenzie,3
411,894-20781,894,St. Gregory/ 69 St SW/Strathcona,3
412,895-20781,895,St. Gregory/ West Springs/ CougarRidge,3
413,896-20781,896,LOA/ Bowness/ Valley Ridge,3

In [10]:
# verify any invalid entries 
# ensure all route ids are unique
print("Duplicate route_ids:", unique_column(routes, 'route_id'))

# check 'route_types' codes
invalid_route_type = routes[~routes['route_type'].isin([0,1,2,3,4,5,6,7,11,12])]['route_id'].tolist()
print("Trips with invalid route_type:", invalid_route_type)

Duplicate route_ids: []
Trips with invalid route_type: []

---

## Stop Times

The `stop_times` data tells us information regarding transit stop times across Calgary. 

Includes the following columns:
- `trip_id`: **Identifies a trip**. References `trip_id` from `trips.txt`
- `arrival_time`: **Arrival time at the stop for a specific trip**. If there are not separate times for arrival and departure at a stop, `arrival_time` and `departure_time` should be the same. For times occurring after midnight on the service day, the time is entered as a value greater than 24:00:00 in HH:MM:SS.
- `departure_time`: **Departure time from the stop for a specific tri**p. For times occurring after midnight on the service day, the time is entered as a value greater than 24:00:00 in HH:MM:SS.
- `stop_id`: **Identifies the serviced stop**. A stop may be serviced multiple times in the same trip, and multiple trips and routes may service the same stop. References `stop_id` from `stops.txt`
- `stop_sequence`: **Order of stops, location groups, or GeoJSON locations for a particular trip**. The values must increase along the trip but do not need to be consecutive.
- `pickup_type`: **Indicates pickup method**. Valid options are:
    - `0` or empty - Regularly scheduled pickup.
    - `1` - No pickup available.
    - `2` - Must phone agency to arrange pickup.
    - `3` - Must coordinate with driver to arrange pickup.
- `drop_off_type`: **Indicates drop off method**. Valid options are:
    - `0` or empty - Regularly scheduled drop off.
    - `1` - No drop off available.
    - `2` - Must phone agency to arrange drop off.
    - `3` - Must coordinate with driver to arrange drop off.
- `shape_dist_traveled`: **Actual distance traveled along the associated shape, from the first stop to the stop specified in this record**. This field specifies how much of the shape to draw between any two stops during a trip. Values used for `shape_dist_traveled` must increase along with the `stop_sequence` field; they must not be used to show reverse travel along a route.
- `timepoint`: **Indicates if arrival and departure times for a stop are strictly adhered to by the vehicle or if they are instead approximate and/or interpolated times**. Valid options are:
    - `0` - Times are considered approximate.
    - `1` - Times are considered exact.

*For further information, refer to the official GTFS documentation (https://gtfs.org/documentation/schedule/reference/#stop_timestxt).*

In [11]:
schema(stop_times)
stop_times.head()

(3699315, 9)

Data Types:
trip_id                  int64
arrival_time            object
departure_time          object
stop_id                  int64
stop_sequence            int64
pickup_type              int64
drop_off_type            int64
shape_dist_traveled    float64
timepoint                int64
dtype: object

Missing Entries:
trip_id                0
arrival_time           0
departure_time         0
stop_id                0
stop_sequence          0
pickup_type            0
drop_off_type          0
shape_dist_traveled    0
timepoint              0
dtype: int64

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,shape_dist_traveled,timepoint
0,74468238,11:52:00,11:52:00,6451,1,0,0,0.000,1
1,74468238,11:53:00,11:53:00,6712,2,0,0,0.557,0
2,74468238,11:53:00,11:53:00,7276,3,0,0,0.866,0
3,74468238,11:59:00,11:59:00,8058,4,0,0,5.359,1
4,74468238,12:00:00,12:00:00,6338,5,0,0,5.659,0

In [12]:
# drop columns we will not be using for this project
stop_times = stop_times.drop(['departure_time', 'pickup_type', 'drop_off_type', 'timepoint', 'shape_dist_traveled'], axis=1)
stop_times

          trip_id arrival_time  stop_id  stop_sequence
0        74468238     11:52:00     6451              1
1        74468238     11:53:00     6712              2
2        74468238     11:53:00     7276              3
3        74468238     11:59:00     8058              4
4        74468238     12:00:00     6338              5
...           ...          ...      ...            ...
3699310  74828111     22:27:00     6809             12
3699311  74828111     22:29:00     9385             13
3699312  74828111     22:32:00     9896             14
3699313  74828111     22:34:00     9396             15
3699314  74828111     22:37:00     9398             16

[3699315 rows x 4 columns]

In [13]:
# fix timeformat of stop_times --> convert to seconds since midnight (of the referenced day)
def seconds_from_midnight(timestamp):
    h,m,s = map(int, timestamp.split(":"))
    return int(h*3600 + m*60 + s)

stop_times['arrival_time'] = stop_times['arrival_time'].apply(seconds_from_midnight)
stop_times.head()

    trip_id  arrival_time  stop_id  stop_sequence
0  74468238         42720     6451              1
1  74468238         42780     6712              2
2  74468238         42780     7276              3
3  74468238         43140     8058              4
4  74468238         43200     6338              5

explanation of sorting the stop_times for edge list

In [14]:
# sort to group trip_ids together, and resort stop_sequences 
stop_times = stop_times.sort_values(by=['trip_id', 'stop_sequence'])
stop_times.head(30)

          trip_id  arrival_time  stop_id  stop_sequence
3622952  72471336         17640     3641              1
3622953  72471336         17820     3817              2
3622954  72471336         18060     3960              3
3622955  72471336         18240     6815              4
3622956  72471336         18360     8566              5
3622957  72471336         18480     8565              6
3622958  72471336         18660     8564              7
3622959  72471336         18780     8563              8
3622960  72471336         18900     8562              9
3622961  72471336         19200     6827             10
3622962  72471336         19260     6828             11
3622963  72471336         19380     6829             12
3622964  72471336         19500     6830             13
3622965  72471336         19560     6831             14
3622966  72471336         19740     8556             15
3622967  72471336         19860     8557             16
3622968  72471336         20040     8558             17
3622969  72471336         20280     8559             18
3622970  72471336         20460     8560             19
3622971  72471336         20580     8561             20
3622972  72471336         20700     9263             21
3622973  72471336         20880     9264             22
3622974  72471336         21000     9387             23
3622975  72471336         21120     9392             24
3622976  72471336         21300     9386             25
3622977  72471339         14580     6802              1
3622978  72471339         14700     6803              2
3622979  72471339         14880     6804              3
3622980  72471339         15060     6805              4
3622981  72471339         15240     6806              5

In [15]:
# verify any invalid entries 
# ensure 'arrival_time' have no negative or invalid entries
invalid_arrival_times = stop_times[stop_times['arrival_time'] < 0]['trip_id'].tolist()
print("Trips with invalid arrival times:", invalid_arrival_times) 

# ensure stop_sequence is in increasing order for each distinct trip (checked under trip_id)
invalid_stop_sequences = (stop_times.groupby('trip_id')['stop_sequence'].apply(lambda x: not (x.is_monotonic_increasing and x.is_unique)))
print(f"Trips with invalid stop_sequence: {invalid_stop_sequences[invalid_stop_sequences].index.tolist()}")

Trips with invalid arrival times: []
Trips with invalid stop_sequence: []

---

## Trips

The `trips` data tells us information regarding trips that transits will take across Calgary. 

Includes the following columns:
- `route_id`: **Identifies a route**.
- `service_id`: **Identifies a set of dates when service is available for one or more routes**.
- `trip_id`: **Identifies a trip**.
- `trip_headsign`: **Text that appears on signage identifying the trip's destination to riders**. This field is recommended for all services with headsign text displayed on the vehicle which may be used to distinguish amongst trips in a route.
- `direction_id`: **Indicates the direction of travel for a trip**. This field should not be used in routing; it provides a way to separate trips by direction when publishing time tables. Valid options are:
    - `0`: Travel in one direction (e.g. outbound travel).
    - `1`: Travel in the opposite direction (e.g. inbound travel).
- `block_id`: **Identifies the block to which the trip belongs**. A block consists of a single trip or many sequential trips made using the same vehicle, defined by shared service days and `block_id`. A `block_id` may have trips with different service days, making distinct blocks. 
- `shape_id`: **Identifies a geospatial shape describing the vehicle travel path for a trip**.

*For further information, refer to the official GTFS documentation (https://gtfs.org/documentation/schedule/reference/#tripstxt).*

In [16]:
schema(trips)
trips.head()

(111146, 7)

Data Types:
route_id         object
service_id       object
trip_id           int64
trip_headsign    object
direction_id      int64
block_id          int64
shape_id          int64
dtype: object

Missing Entries:
route_id         0
service_id       0
trip_id          0
trip_headsign    0
direction_id     0
block_id         0
shape_id         0
dtype: int64

,route_id,service_id,trip_id,trip_headsign,direction_id,block_id,shape_id
0,36-20789,2026JU-1BUSSA-Saturday-02,74468238,RIVERBEND,0,7144090,360037
1,36-20789,2026JU-1BUSSA-Saturday-02,74468239,RIVERBEND,0,7144090,360037
2,36-20789,2026JU-1BUSSA-Saturday-02,74468240,RIVERBEND,0,7144090,360037
3,36-20789,2026JU-1BUSSA-Saturday-02,74468241,RIVERBEND,0,7144090,360037
4,36-20789,2026JU-1BUSSA-Saturday-02,74468242,RIVERBEND,0,7144090,360037

In [17]:
# drop columns we will not be using for this project
trips = trips.drop(['trip_headsign', 'block_id'], axis=1)
trips

         route_id                 service_id   trip_id  direction_id  shape_id
0        36-20789  2026JU-1BUSSA-Saturday-02  74468238             0    360037
1        36-20789  2026JU-1BUSSA-Saturday-02  74468239             0    360037
2        36-20789  2026JU-1BUSSA-Saturday-02  74468240             0    360037
3        36-20789  2026JU-1BUSSA-Saturday-02  74468241             0    360037
4        36-20789  2026JU-1BUSSA-Saturday-02  74468242             0    360037
...           ...                        ...       ...           ...       ...
111141  202-20780  2026MA-pT7Jun14-Sunday-01  74828106             1   2020435
111142  202-20780  2026MA-pT7Jun14-Sunday-01  74828108             1   2020435
111143  202-20780  2026MA-pT7Jun14-Sunday-01  74828109             0   2020436
111144  202-20780  2026MA-pT7Jun14-Sunday-01  74828110             1   2020435
111145  202-20780  2026MA-pT7Jun14-Sunday-01  74828111             0   2020436

[111146 rows x 5 columns]

In [18]:
# verify any invalid entries 
# ensure all trip_ids are unique
print("Duplicate trip_ids:", unique_column(trips, 'trip_id'))

# 'direction_id' codes
invalid_direction_ids = trips[~trips['direction_id'].isin([0,1])]['trip_id'].tolist()
print("Trips with invalid direction_id:", invalid_direction_ids)

Duplicate trip_ids: []
Trips with invalid direction_id: []

---

## Calendar

The `calendar` data tells us information regarding service operations for transit routes across Calgary. 

Includes the following columns:
- `service_id`: **Identifies a set of dates when service is available for one or more routes**.
- `monday`: **Indicates whether the service operates on all Mondays in the date range specified by the `start_date` and ``end_date`` fields**. 
    - `1` - Service is available for all Mondays in the date range.
    - `0` - Service is not available for Mondays in the date range.
- `tuesday`: Functions in the same way as `monday` except applies to Tuesdays
- `wednesday`: Functions in the same way as `monday` except applies to Wednesdays
- `thursday`: Functions in the same way as `monday` except applies to Thursdays
- `friday`: Functions in the same way as `monday` except applies to Fridays
- `saturday`: Functions in the same way as `monday` except applies to Saturdays
- `sunday`: Functions in the same way as `monday` except applies to Sundays
- `start_date`: **Starting service day for the service interval**.
- `end_date`: **End service day for the service interval**. This service day is included in the interval.

*For further information, refer to the official GTFS documentation (https://gtfs.org/documentation/schedule/reference/#calendartxt).*

In [19]:
schema(calendar)
calendar.head()

(33, 10)

Data Types:
service_id    object
monday         int64
tuesday        int64
wednesday      int64
thursday       int64
friday         int64
saturday       int64
sunday         int64
start_date     int64
end_date       int64
dtype: object

Missing Entries:
service_id    0
monday        0
tuesday       0
wednesday     0
thursday      0
friday        0
saturday      0
sunday        0
start_date    0
end_date      0
dtype: int64

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,2026MA-1BUSWK-Weekday-03,1,1,1,1,1,0,0,20260603,20260619
1,2026MA-1BUSWK-Weekday-03-1111000,1,1,1,1,0,0,0,20260603,20260619
2,2026MA-1BUSWK-Weekday-03-0000100,0,0,0,0,1,0,0,20260603,20260619
3,2026MA-1BUSSA-Saturday-03,0,0,0,0,0,1,0,20260606,20260620
4,2026MA-1BUSSU-Sunday-03,0,0,0,0,0,0,1,20260607,20260621

In [20]:
# convert start_date and end_date to proper datetime format
calendar['start_date'] = calendar['start_date'].apply(lambda row: datetime.strptime(str(row), "%Y%m%d"))
calendar['end_date'] = calendar['end_date'].apply(lambda row: datetime.strptime(str(row), "%Y%m%d"))
calendar.head()

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,2026MA-1BUSWK-Weekday-03,1,1,1,1,1,0,0,2026-06-03,2026-06-19
1,2026MA-1BUSWK-Weekday-03-1111000,1,1,1,1,0,0,0,2026-06-03,2026-06-19
2,2026MA-1BUSWK-Weekday-03-0000100,0,0,0,0,1,0,0,2026-06-03,2026-06-19
3,2026MA-1BUSSA-Saturday-03,0,0,0,0,0,1,0,2026-06-06,2026-06-20
4,2026MA-1BUSSU-Sunday-03,0,0,0,0,0,0,1,2026-06-07,2026-06-21

In [21]:
# verify any invalid entries 
# 'days of the week' codes
days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']
for day in days:
    invalid_day_code = calendar[~calendar[day].isin([0,1])]['service_id'].tolist()
    print(f"Trips with invalid {day}_code:", invalid_day_code)

Trips with invalid monday_code: []
Trips with invalid tuesday_code: []
Trips with invalid wednesday_code: []
Trips with invalid thursday_code: []
Trips with invalid friday_code: []
Trips with invalid saturday_code: []
Trips with invalid sunday_code: []

In [22]:
# verify all start_dates start before end_date
invalid_dates = calendar['start_date'] > calendar['end_date']
print("Dates where start_date comes after end_date:", calendar[invalid_dates]['service_id'].tolist())

Dates where start_date comes after end_date: []

---

## Calendar Dates

The `calendar_dates` data tells us information regarding exceptions for usual service operations for transit routes across Calgary. 

Includes the following columns:
- `service_id`: **A code identifying a scheduled service pattern used to link trips to the days they run**. For example `2026JU-1BUSWK-Weekday-02`:
    - `2026JU` - represents year and month where service exception occurs (June 2026)
    - `1BUS` - represents transit service being affected (Bus)
    - `WK` - represents the day of the week where exception occurs (Weekday)
    - `Weekday-02` - reiterates day of the week and iteration/version of this exception update (reiterates Weekday, and is the 2nd version of this exception update).
- `date`: Date when service exception occurs.
- `exception_type`: **Indicates whether service is available on the date specified in the date field**. Valid options are:
   - `1` - Service has been added for the specified date.
   - `2` - Service has been removed for the specified date.

*For further information, refer to the official GTFS documentation (https://gtfs.org/documentation/schedule/reference/#calendar_datestxt).*

In [23]:
schema(calendar_dates)
calendar_dates.head()

(31, 3)

Data Types:
service_id        object
date               int64
exception_type     int64
dtype: object

Missing Entries:
service_id        0
date              0
exception_type    0
dtype: int64

                 service_id      date  exception_type
0  2026JU-1BUSWK-Weekday-02  20260701               2
1  2026JU-1BUSWK-Weekday-02  20260702               2
2  2026JU-1BUSWK-Weekday-02  20260703               2
3  2026JU-1BUSWK-Weekday-02  20260706               2
4  2026JU-1BUSWK-Weekday-02  20260707               2

In [24]:
# convert date into proper datetime format 
from datetime import datetime

calendar_dates['date'] = calendar_dates['date'].apply(lambda row: datetime.strptime(str(row), "%Y%m%d"))
calendar_dates.head()

                 service_id       date  exception_type
0  2026JU-1BUSWK-Weekday-02 2026-07-01               2
1  2026JU-1BUSWK-Weekday-02 2026-07-02               2
2  2026JU-1BUSWK-Weekday-02 2026-07-03               2
3  2026JU-1BUSWK-Weekday-02 2026-07-06               2
4  2026JU-1BUSWK-Weekday-02 2026-07-07               2

In [25]:
# verify any invalid entries 
# 'exception_type' codes
invalid_exception_codes = calendar_dates[~calendar_dates['exception_type'].isin([1,2])]['service_id'].tolist()
print(f"Trips with invalid exception_type:", invalid_exception_codes)

Trips with invalid exception_type: []

---

## Shapes

The `shapes` data tells us information describing the paths that a transit vehicle travels along its route across Calgary. Shapes are associated with Trips, and consist of a sequence of points through which the vehicle passes in order. Shapes do not need to intercept the location of Stops exactly, but all Stops on a trip should lie within a small distance of the shape for that trip, i.e. close to straight line segments connecting the shape points. 

Includes the following columns:
- `shape_id`: **Identifies a shape**.
- `shape_pt_lat`: **Latitude of a shape point**.
- `shape_pt_lon`: **Longitude of a shape point**.
- `shape_pt_sequence`: **Sequence in which the shape points connect to form the shape. Values must increase along the trip but do not need to be consecutive**.
- `shape_dist_traveled`: **Actual distance traveled along the shape from the first shape point to the point specified in this record**. Values must increase along with `shape_pt_sequence`; they must not be used to show reverse travel along a route.

*For further information, refer to the official GTFS documentation (https://gtfs.org/documentation/schedule/reference/#shapestxt).*

In [26]:
schema(shapes)
shapes.head()

(384646, 5)

Data Types:
shape_id                 int64
shape_pt_lat           float64
shape_pt_lon           float64
shape_pt_sequence        int64
shape_dist_traveled    float64
dtype: object

Missing Entries:
shape_id               0
shape_pt_lat           0
shape_pt_lon           0
shape_pt_sequence      0
shape_dist_traveled    0
dtype: int64

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
0,10180,51.052002,-113.941285,10001,0.000
1,10180,51.052017,-113.941298,10002,0.002
2,10180,51.052050,-113.941350,10003,0.007
3,10180,51.052061,-113.941391,10004,0.010
4,10180,51.052065,-113.941431,10005,0.013

In [27]:
# verify any invalid entries 
# ensure 'shape_pt_sequence' is increasing for each distinct trip (shape_id)
invalid_sequences = (shapes.groupby('shape_id')['shape_pt_sequence'].apply(lambda x: not (x.is_monotonic_increasing and x.is_unique)))
print(f"Shapes with invalid shape_pt_sequence: {invalid_sequences[invalid_sequences].index.tolist()}")

Shapes with invalid shape_pt_sequence: []

---

## Foreign Key Validations

description

In [28]:
# key validation helper function
def validate_keys(df1, df2, id_name, df1_name, df2_name):
    key_col1 = set(df1[id_name])
    key_col2 = set(df2[id_name])

    # check if each and every element from df1 in the id_name column is the same as each element in the df2 id_name column
    if key_col1 == key_col2:
        print(f"all {id_name}s exist and are the same in both tables.")

    else:
        # determine if ids that exist from df1 do not exist in df2 
        in_df1_but_not_df2 = key_col1 - key_col2
        if in_df1_but_not_df2:
            print(f"Missing items from {df1_name} not found in {df2_name}: {sorted(in_df1_but_not_df2)}") 

        # determine if ids that exist from df2 do not exist in df1
        in_df2_but_not_df1 = key_col2 - key_col1
        if in_df2_but_not_df1:
            print(f"Missing items from {df2_name} not found in {df1_name}:  {sorted(in_df2_but_not_df1)}")

In [29]:
# check every `stop_id` from the `stop_times` table each also all exists in the `stops` file 
validate_keys(stops, stop_times, 'stop_id', 'stops', 'stop_times') 

# check every `trip_id` from the `stop_times` table each also all exists in the `trips` file 
validate_keys(trips, stop_times, 'trip_id', 'trips', 'stop_times') 

# check every `route_id` from the `trips` table each also all exists in the `routes` file 
validate_keys(routes, trips, 'route_id', 'routes', 'trips')

all stop_ids exist and are the same in both tables.
all trip_ids exist and are the same in both tables.
all route_ids exist and are the same in both tables.

---

## Edge List

In [30]:
# create new dataframe for stop_total_times -- creating 'edges' between each stop and getting total time taken to get from one stop to the next
stop_total_times = stop_times[['trip_id', 'stop_sequence', 'arrival_time', 'stop_id']].copy()
stop_total_times['to_stop'] = stop_total_times.groupby('trip_id')['stop_id'].shift(-1) # create `to_stop` column -- stop_id of the stop the transit is heading to
stop_total_times['end_time'] = stop_total_times.groupby('trip_id')['arrival_time'].shift(-1) # create `end_time` column -- time since midnight when arriving at next stop
stop_total_times = stop_total_times.dropna(subset=['to_stop', 'end_time']) # remove NaN entries from shifting
stop_total_times = stop_total_times.astype(int) # convert entries back to int

stop_total_times = stop_total_times.rename(columns={'stop_id': 'from_stop'})
stop_total_times.head(30)

          trip_id  stop_sequence  arrival_time  from_stop  to_stop  end_time
3622952  72471336              1         17640       3641     3817     17820
3622953  72471336              2         17820       3817     3960     18060
3622954  72471336              3         18060       3960     6815     18240
3622955  72471336              4         18240       6815     8566     18360
3622956  72471336              5         18360       8566     8565     18480
3622957  72471336              6         18480       8565     8564     18660
3622958  72471336              7         18660       8564     8563     18780
3622959  72471336              8         18780       8563     8562     18900
3622960  72471336              9         18900       8562     6827     19200
3622961  72471336             10         19200       6827     6828     19260
3622962  72471336             11         19260       6828     6829     19380
3622963  72471336             12         19380       6829     6830     19500
3622964  72471336             13         19500       6830     6831     19560
3622965  72471336             14         19560       6831     8556     19740
3622966  72471336             15         19740       8556     8557     19860
3622967  72471336             16         19860       8557     8558     20040
3622968  72471336             17         20040       8558     8559     20280
3622969  72471336             18         20280       8559     8560     20460
3622970  72471336             19         20460       8560     8561     20580
3622971  72471336             20         20580       8561     9263     20700
3622972  72471336             21         20700       9263     9264     20880
3622973  72471336             22         20880       9264     9387     21000
3622974  72471336             23         21000       9387     9392     21120
3622975  72471336             24         21120       9392     9386     21300
3622977  72471339              1         14580       6802     6803     14700
3622978  72471339              2         14700       6803     6804     14880
3622979  72471339              3         14880       6804     6805     15060
3622980  72471339              4         15060       6805     6806     15240
3622981  72471339              5         15240       6806     6807     15360
3622982  72471339              6         15360       6807     6822     15540

explain why trip time of 0 or less is bad -- only for this edge list

In [31]:
# calculate travel time
stop_total_times['trip_time'] = stop_total_times['end_time'] - stop_total_times['arrival_time']

# verify there are no negative or 0 entries for trip time (invalid entries)
invalid_trip_times = stop_total_times['trip_time'] <= 0
print("Trips with invalid trip_time:", stop_total_times[invalid_trip_times]['trip_id'].unique().tolist())

Trips with invalid trip_time: [73224970, 73224971, 73224972, 73224973, 73224974, 73224975, 73224976, 73224977, 73224978, 73224979, 73224980, 73224981, 73224982, 73224983, 73224984, 73224985, 73224986, 73224987, 73224988, 73224989, 73224990, 73224991, 73224992, 73224993, 73224994, 73224995, 73224996, 73224997, 73224998, 73224999, 73225000, 73225001, 73225002, 73225003, 73225004, 73225005, 73225006, 73225007, 73225008, 73225009, 73225010, 73225011, 73225012, 73225013, 73225014, 73225015, 73225016, 73225017, 73225018, 73225019, 73225020, 73225021, 73225022, 73225023, 73225024, 73225025, 73225026, 73225027, 73225028, 73225029, 73225030, 73225031, 73225032, 73225033, 73225034, 73225035, 73225036, 73225037, 73225038, 73225039, 73225040, 73225041, 73225042, 73225043, 73225044, 73225045, 73225046, 73225047, 73225048, 73225049, 73225050, 73225051, 73225052, 73225053, 73225054, 73225055, 73225056, 73225057, 73225058, 73225059, 73225060, 73225061, 73225062, 73225063, 73225064, 73225065, 73225066, 73225067, 73225068, 73225069, 73225070, 73225071, 73225072, 73225073, 73225074, 73225075, 73225076, 73225077, 73225078, 73225079, 73225080, 73225081, 73225082, 73225083, 73225084, 73225085, 73225086, 73225087, 73225088, 73225089, 73225090, 73225091, 73225092, 73225093, 73225094, 73225095, 73225096, 73225097, 73225098, 73225099, 73225100, 73225101, 73225102, 73225103, 73225104, 73225105, 73225106, 73225107, 73225108, 73225109, 73225110, 73225111, 73225112, 73225113, 73225114, 73225115, 73225116, 73225117, 73225118, 73225119, 73225120, 73225121, 73225122, 73225123, 73225124, 73225125, 73225126, 73225127, 73225128, 73225129, 73225130, 73225131, 73225132, 73225133, 73225134, 73225135, 73225136, 73225137, 73225138, 73225139, 73225140, 73225141, 73225142, 73225143, 73225144, 73225145, 73225146, 73225147, 73225148, 73225149, 73225150, 73225151, 73225152, 73225153, 73225154, 73225155, 73225156, 73225157, 73225158, 73225159, 73225160, 73225161, 73225162, 73225163, 73225164, 73225165, 73225166, 73225167, 73225168, 73225169, 73225170, 73225171, 73225173, 73225174, 73225175, 73225176, 73225177, 73225178, 73225179, 73225180, 73225181, 73225182, 73225183, 73225184, 73225185, 73225186, 73225187, 73225188, 73225189, 73225190, 73225191, 73225192, 73225193, 73225194, 73225195, 73225196, 73225197, 73225198, 73225199, 73225200, 73225201, 73225202, 73225203, 73225204, 73225205, 73225206, 73225207, 73225208, 73225209, 73225210, 73225211, 73225212, 73225213, 73225214, 73225215, 73225216, 73225217, 73225218, 73225219, 73225220, 73225221, 73225222, 73225223, 73225224, 73225225, 73225226, 73225227, 73225228, 73225229, 73225230, 73225231, 73225232, 73225233, 73225234, 73225235, 73225236, 73225237, 73225238, 73225239, 73225240, 73225241, 73225242, 73225243, 73225244, 73225245, 73225246, 73225247, 73225248, 73225249, 73225250, 73225251, 73225252, 73225253, 73225254, 73225255, 73225256, 73225257, 73225258, 73225259, 73225260, 73225261, 73225262, 73225263, 73225264, 73225265, 73225266, 73225267, 73225268, 73225269, 73225270, 73225271, 73225272, 73225273, 73225274, 73225275, 73225276, 73225277, 73225278, 73225279, 73225280, 73225281, 73225282, 73225283, 73225284, 73225285, 73225286, 73225287, 73225288, 73225289, 73225290, 73225291, 73225292, 73225293, 73225294, 73225295, 73225296, 73225297, 73225298, 73225299, 73225300, 73225301, 73225302, 73225303, 73225304, 73225305, 73225306, 73225307, 73225308, 73225309, 73225310, 73225311, 73225312, 73225313, 73225314, 73225315, 73225316, 73225317, 73225318, 73225319, 73225320, 73225321, 73225322, 73225323, 73225324, 73225325, 73225326, 73225327, 73225328, 73225329, 73225330, 73225331, 73225332, 73225333, 73225334, 73225335, 73225336, 73225337, 73225338, 73225339, 73225340, 73225341, 73225342, 73225344, 73225345, 73225346, 73225347, 73225348, 73225349, 73225350, 73225351, 73225352, 73225353, 73225354, 73225355, 73225356, 73225357, 73225358, 73225359, 73225360, 73225361, 73225362, 73225363, 73225364, 73225365, 73225366, 73225367, 73225368, 73225369, 73225370, 73225371, 73225372, 73225373, 73225374, 73225375, 73225376, 73225377, 73225378, 73225379, 73225380, 73225381, 73225382, 73225383, 73225384, 73225385, 73225386, 73225387, 73225388, 73225389, 73225390, 73225391, 73225392, 73225393, 73225394, 73225395, 73225396, 73225397, 73225398, 73225399, 73225400, 73225401, 73225402, 73225403, 73225404, 73225405, 73225406, 73225407, 73225408, 73225409, 73225410, 73225411, 73225412, 73225413, 73225414, 73225415, 73225416, 73225417, 73225418, 73225419, 73225420, 73225421, 73225422, 73225423, 73225424, 73225425, 73225426, 73225427, 73225428, 73225429, 73225430, 73225431, 73225432, 73225433, 73225434, 73225435, 73225436, 73225437, 73225438, 73225439, 73225440, 73225441, 73225442, 73225443, 73225444, 73225445, 73225446, 73225447, 73225448, 73225449, 73225450, 73225451, 73225452, 73225453, 73225454, 73225455, 73225456, 73225457, 73225458, 73225459, 73225460, 73225461, 73225462, 73225463, 73225464, 73225465, 73225466, 73225467, 73225468, 73225469, 73225470, 73225471, 73225472, 73225473, 73225474, 73225475, 73225476, 73225477, 73225478, 73225479, 73225480, 73225481, 73225482, 73225483, 73225484, 73225485, 73225486, 73225487, 73225488, 73225489, 73225490, 73225491, 73225492, 73225493, 73225494, 73225495, 73225496, 73225497, 73225498, 73225499, 73225500, 73225501, 73225502, 73225503, 73225504, 73225505, 73225506, 73225507, 73225508, 73225509, 73225510, 73225511, 73225512, 73225513, 73225514, 73225515, 73225516, 73225517, 73225518, 73225519, 73225520, 73225521, 73225522, 73225523, 73225524, 73225525, 73225526, 73225527, 73225528, 73225529, 73225530, 73225531, 73225532, 73225533, 73225534, 73225535, 73225536, 73225537, 73225538, 73225539, 73225540, 73225541, 73225542, 73225543, 73225544, 73225545, 73225546, 73225547, 73225548, 73225549, 73225550, 73225551, 73225552, 73225553, 73225554, 73225555, 73225556, 73225557, 73225558, 73225559, 73225560, 73225561, 73225562, 73225563, 73225564, 73225565, 73225566, 73225567, 73225568, 73225569, 73225570, 73225571, 73225572, 73225573, 73225574, 73225575, 73225576, 73225577, 73225578, 73225579, 73225580, 73225581, 73225582, 73225583, 73225584, 73225585, 73225586, 73225587, 73225588, 73225589, 73225590, 73225591, 73225592, 73225593, 73225594, 73225595, 73225596, 73225597, 73225598, 73225599, 73225600, 73225601, 73225602, 73225603, 73225604, 73225605, 73225606, 73225607, 73225608, 73225609, 73225610, 73225611, 73225612, 73225615, 73225617, 73225619, 73225622, 73225624, 73225626, 73225628, 73225630, 73225633, 73225634, 73225636, 73225637, 73225639, 73225641, 73225644, 73225647, 73225649, 73225650, 73225652, 73225654, 73225657, 73225659, 73225660, 73225662, 73225665, 73225667, 73225668, 73225670, 73225671, 73225673, 73225676, 73225678, 73225680, 73225682, 73225684, 73225685, 73225687, 73225689, 73225691, 73225693, 73225696, 73225698, 73225700, 73225702, 73225704, 73225706, 73225707, 73225708, 73225710, 73225713, 73225715, 73225716, 73225717, 73225718, 73225719, 73225720, 73225721, 73225722, 73225723, 73225724, 73225725, 73225726, 73225727, 73225728, 73225729, 73225730, 73225731, 73225732, 73225733, 73225734, 73225735, 73225737, 73225738, 73225740, 73225742, 73225743, 73225746, 73225748, 73225749, 73225750, 73225752, 73225753, 73225754, 73225755, 73225756, 73225757, 73225758, 73225759, 73225760, 73225761, 73225762, 73225763, 73225764, 73225765, 73225766, 73225767, 73225768, 73225769, 73225770, 73225771, 73225772, 73225773, 73225774, 73225775, 73225776, 73225777, 73225778, 73225779, 73225780, 73225781, 73225782, 73225783, 73225784, 73225785, 73225786, 73225787, 73225788, 73225789, 73225790, 73225791, 73225792, 73225793, 73225794, 73225795, 73225796, 73225797, 73225798, 73225799, 73225800, 73225801, 73225802, 73225803, 73225804, 73225805, 73225806, 73225807, 73225808, 73225809, 73225810, 73225811, 73225812, 73225813, 73225814, 73225815, 73225816, 73225817, 73225818, 73225819, 73225820, 73225821, 73225822, 73225823, 73225824, 73225825, 73225826, 73225827, 73225828, 73225829, 73225830, 73225831, 73225832, 73225833, 73225834, 73225835, 73225836, 73225837, 73225838, 73225839, 73225840, 73225841, 73225842, 73225843, 73225844, 73225845, 73225846, 73225847, 73225848, 73225849, 73225850, 73225851, 73225852, 73225853, 73225854, 73225855, 73225856, 73225857, 73225858, 73225859, 73225860, 73225861, 73225862, 73225863, 73225864, 73225865, 73225866, 73225867, 73225868, 73225869, 73225870, 73225871, 73225872, 73225873, 73225874, 73225875, 73225876, 73225877, 73225878, 73225879, 73225880, 73225881, 73225882, 73225883, 73225884, 73225885, 73225886, 73225887, 73225888, 73225889, 73225890, 73225891, 73225892, 73225893, 73225894, 73225895, 73225896, 73225897, 73225898, 73225899, 73225900, 73225901, 73225902, 73225903, 73225904, 73225905, 73225906, 73225907, 73225908, 73225909, 73225910, 73225911, 73225912, 73225913, 73225914, 73225915, 73225916, 73225917, 73225918, 73225919, 73225920, 73225921, 73225922, 73225923, 73225924, 73225925, 73225926, 73225927, 73225928, 73225929, 73225930, 73225931, 73225932, 73225933, 73225934, 73225935, 73225936, 73225937, 73225938, 73225939, 73225940, 73225941, 73225942, 73225944, 73225945, 73225946, 73225947, 73225948, 73225949, 73225950, 73225951, 73225952, 73225953, 73225954, 73225955, 73225956, 73225957, 73225958, 73225959, 73225960, 73225961, 73225962, 73225963, 73225964, 73225965, 73225966, 73225967, 73225968, 73225969, 73225970, 73225971, 73225972, 73225973, 73225974, 73225975, 73225976, 73225977, 73225978, 73225979, 73225980, 73225981, 73225982, 73225983, 73225984, 73225985, 73225986, 73225987, 73225988, 73225989, 73225990, 73225991, 73225992, 73225993, 73225994, 73225995, 73225996, 73225997, 73225998, 73225999, 73226000, 73226001, 73226002, 73226003, 73226004, 73226005, 73226006, 73226007, 73226008, 73226009, 73226010, 73226011, 73226012, 73226013, 73226014, 73226015, 73226016, 73226017, 73226018, 73226019, 73226020, 73226021, 73226022, 73226023, 73226024, 73226025, 73226026, 73226027, 73226028, 73226029, 73226030, 73226031, 73226032, 73226033, 73226034, 73226035, 73226036, 73226037, 73226038, 73226039, 73226040, 73226041, 73226042, 73226043, 73226044, 73226045, 73226046, 73226047, 73226048, 73226049, 73226050, 73226051, 73226052, 73226053, 73226054, 73226055, 73226056, 73226057, 73226058, 73226059, 73226060, 73226061, 73226062, 73226063, 73226064, 73226065, 73226066, 73226067, 73226068, 73226069, 73226070, 73226071, 73226072, 73226073, 73226074, 73226075, 73226076, 73226077, 73226078, 73226079, 73226080, 73226081, 73226082, 73226083, 73226084, 73226085, 73226086, 73226087, 73226088, 73226089, 73226090, 73226091, 73226092, 73226093, 73226094, 73226095, 73226096, 73226097, 73226098, 73226099, 73226100, 73226101, 73226102, 73226103, 73226104, 73226105, 73226106, 73226107, 73226108, 73226109, 73226110, 73226111, 73226112, 73226113, 73226114, 73226115, 73226116, 73226117, 73226118, 73226119, 73226120, 73226121, 73226122, 73226123, 73226124, 73226125, 73226126, 73226127, 73226128, 73226129, 73226130, 73226131, 73226133, 73226134, 73226135, 73226136, 73226138, 73226139, 73226140, 73226141, 73226142, 73226144, 73226145, 73226146, 73226147, 73226148, 73226150, 73226151, 73226153, 73226154, 73226156, 73226157, 73226158, 73226159, 73226161, 73226162, 73226164, 73226165, 73226166, 73226167, 73226169, 73226170, 73226171, 73226173, 73226174, 73226175, 73226176, 73226177, 73226178, 73226179, 73226180, 73226181, 73226182, 73226184, 73226185, 73226186, 73226187, 73226189, 73226190, 73226191, 73226193, 73226194, 73226196, 73226197, 73226198, 73226200, 73226201, 73226202, 73226203, 73226205, 73226206, 73226207, 73226209, 73226210, 73226212, 73226213, 73226214, 73226215, 73226216, 73226217, 73226218, 73226219, 73226220, 73226221, 73226222, 73226224, 73226225, 73226226, 73226227, 73226229, 73226230, 73226231, 73226232, 73226233, 73226235, 73226237, 73226238, 73226239, 73226240, 73226243, 73226244, 73226245, 73226246, 73226247, 73226249, 73226250, 73226251, 73226253, 73226254, 73226255, 73226256, 73226258, 73226259, 73226262, 73226263, 73226264, 73226265, 73226266, 73226267, 73226268, 73226269, 73226270, 73226271, 73226272, 73226273, 73226274, 73226275, 73226276, 73226277, 73226278, 73226279, 73226280, 73226281, 73226282, 73226283, 73226284, 73226285, 73226286, 73226287, 73226288, 73226289, 73226290, 73226291, 73226292, 73226293, 73226294, 73226295, 73226296, 73226297, 73226298, 73226300, 73226304, 73226305, 73226306, 73226307, 73226308, 73226309, 73226310, 73226311, 73226312, 73226313, 73226314, 73226315, 73226316, 73226317, 73226318, 73226319, 73226320, 73226321, 73226322, 73226323, 73226324, 73226325, 73226326, 73226327, 73226328, 73226329, 73226330, 73226331, 73226332, 73226333, 73226334, 73226335, 73226336, 73226337, 73226338, 73226339, 73226340, 73226341, 73226342, 73226343, 73226344, 73226347, 73226351, 73226352, 73226353, 73226354, 73226355, 73226356, 73226357, 73226358, 73226359, 73226360, 73226361, 73226362, 73226363, 73226364, 73226365, 73226366, 73226367, 73226368, 73226369, 73226370, 73226371, 73226372, 73226373, 73226374, 73226375, 73226376, 73226377, 73226378, 73226379, 73226380, 73226381, 73226382, 73226383, 73226384, 73226385, 73226386, 73226387, 73226388, 73226389, 73226390, 73226391, 73226392, 73226393, 73226394, 73226395, 73226396, 73226397, 73226398, 73226399, 73226400, 73226401, 73226402, 73226403, 73226404, 73226405, 73226406, 73226407, 73226408, 73226409, 73226410, 73226411, 73226412, 73226413, 73226414, 73226415, 73226416, 73226417, 73226418, 73226419, 73226420, 73226421, 73226422, 73226423, 73226424, 73226425, 73226426, 73226427, 73226428, 73226429, 73226430, 73226431, 73226432, 73226433, 73226434, 73226435, 73226436, 73226437, 73226438, 73226439, 73226440, 73226441, 73226442, 73226443, 73226444, 73226445, 73226446, 73226447, 73226448, 73226449, 73226450, 73226451, 73226452, 73226453, 73226454, 73226455, 73226456, 73226457, 73226458, 73226459, 73226460, 73226461, 73226462, 73226463, 73226464, 73226465, 73226466, 73226467, 73226468, 73226469, 73226470, 73226471, 73226472, 73226473, 73226474, 73226475, 73226476, 73226477, 73226478, 73226479, 73226480, 73226481, 73226482, 73226483, 73226484, 73226485, 73226486, 73226487, 73226488, 73226489, 73226490, 73226491, 73226492, 73226493, 73226494, 73226495, 73226496, 73226497, 73226498, 73226499, 73226500, 73226501, 73226502, 73226503, 73226504, 73226505, 73226506, 73226507, 73226508, 73226509, 73226510, 73226511, 73226512, 73226513, 73226514, 73226515, 73226516, 73226517, 73226518, 73226519, 73226520, 73226521, 73226522, 73226523, 73226524, 73226525, 73226526, 73226527, 73226528, 73226529, 73226530, 73226531, 73226532, 73226533, 73226534, 73226535, 73226536, 73226537, 73226538, 73226539, 73226540, 73226541, 73226542, 73226543, 73226544, 73226545, 73226546, 73226547, 73226548, 73226549, 73226550, 73226551, 73226552, 73226553, 73226554, 73226555, 73226556, 73226557, 73226558, 73226559, 73226560, 73226561, 73226562, 73226563, 73226564, 73226565, 73226566, 73226567, 73226568, 73226569, 73226570, 73226571, 73226572, 73226573, 73226574, 73226575, 73226576, 73226577, 73226578, 73226579, 73226580, 73226581, 73226582, 73226583, 73226584, 73226585, 73226586, 73226587, 73226588, 73226589, 73226590, 73226591, 73226592, 73226593, 73226594, 73226595, 73226596, 73226597, 73226598, 73226599, 73226600, 73226601, 73226602, 73226603, 73226604, 73226605, 73226606, 73226607, 73226608, 73226609, 73226610, 73226611, 73226612, 73226613, 73226614, 73226615, 73226616, 73226617, 73226618, 73226619, 73226620, 73226621, 73226622, 73226623, 73226624, 73226625, 73226626, 73226627, 73226628, 73226629, 73226644, 73226645, 73226646, 73226647, 73226648, 73226649, 73226650, 73226651, 73226652, 73226653, 73226654, 73226655, 73226656, 73226657, 73226658, 73226659, 73226660, 73226661, 73226662, 73226663, 73226664, 73226665, 73226666, 73226667, 73226668, 73226669, 73226670, 73226671, 73226672, 73226677, 73226678, 73226679, 73226680, 73226681, 73226682, 73226683, 73226684, 73226685, 73226686, 73226687, 73226688, 73226689, 73226690, 73226691, 73226692, 73226693, 73226694, 73226695, 73226696, 73226697, 73226698, 73226699, 73226700, 73226701, 73226702, 73226703, 73226704, 73226705, 73226706, 73226707, 73226708, 73226709, 73226710, 73226711, 73226712, 73226713, 73226714, 73226715, 73226716, 73226717, 73226718, 73226719, 73226720, 73226721, 73226722, 73226723, 73226724, 73226725, 73226726, 73226727, 73226728, 73226729, 73226730, 73226731, 73226732, 73226733, 73226734, 73226735, 73226736, 73226737, 73226738, 73226739, 73226740, 73226741, 73226742, 73226743, 73226744, 73226745, 73226746, 73226747, 73226748, 73226749, 73226750, 73226751, 73226752, 73226753, 73226754, 73226755, 73226756, 73226757, 73226758, 73226759, 73226760, 73226761, 73226762, 73226763, 73226764, 73226765, 73226766, 73226767, 73226768, 73226769, 73226770, 73226771, 73226772, 73226773, 73226774, 73226775, 73226776, 73226777, 73226778, 73226779, 73226780, 73226781, 73226782, 73226783, 73226784, 73226785, 73226786, 73226787, 73226788, 73226789, 73226790, 73226791, 73226792, 73226793, 73226794, 73226795, 73226796, 73226797, 73226798, 73226799, 73226800, 73226801, 73226802, 73226803, 73226804, 73226805, 73226806, 73226807, 73226808, 73226809, 73226810, 73226811, 73226812, 73226813, 73226814, 73226815, 73226816, 73226817, 73226818, 73226819, 73226820, 73226821, 73226822, 73226823, 73226824, 73226825, 73226826, 73226827, 73226828, 73226829, 73226830, 73226831, 73226832, 73226833, 73226834, 73226835, 73226836, 73226837, 73226838, 73226839, 73226840, 73226841, 73226842, 73226843, 73226844, 73226845, 73226846, 73226847, 73226848, 73226849, 73226850, 73226851, 73226852, 73226853, 73226854, 73226855, 73226856, 73226857, 73226858, 73226859, 73226860, 73226861, 73226862, 73226863, 73226864, 73226865, 73226866, 73226867, 73226868, 73226869, 73226870, 73226871, 73226872, 73226873, 73226874, 73226875, 73226876, 73226877, 73226878, 73226879, 73226880, 73226881, 73226882, 73226883, 73226884, 73226885, 73226886, 73226887, 73226888, 73226889, 73226890, 73226891, 73226892, 73226893, 73226894, 73226895, 73226896, 73226897, 73226898, 73226899, 73226900, 73226901, 73226902, 73226903, 73226904, 73226905, 73226906, 73226907, 73226908, 73226909, 73226910, 73226911, 73226912, 73226913, 73226914, 73226915, 73226916, 73226917, 73226918, 73226919, 73226920, 73226921, 73226922, 73226923, 73226924, 73226925, 73226926, 73226927, 73226928, 73226929, 73226930, 73226931, 73226932, 73226933, 73226934, 73226935, 73226936, 73226937, 73226938, 73226939, 73226940, 73226941, 73226942, 73226943, 73226944, 73226945, 73226946, 73226947, 73226948, 73226949, 73226950, 73226951, 73226952, 73226953, 73226954, 73226955, 73226956, 73226957, 73226958, 73226959, 73226960, 73226961, 73226962, 73226963, 73226964, 73226965, 73226966, 73226967, 73226968, 73226969, 73226970, 73226971, 73226972, 73226973, 73226974, 73226975, 73226976, 73226977, 73226978, 73226979, 73226980, 73226981, 73226982, 73226983, 73226984, 73226985, 73226986, 73226987, 73226988, 73226989, 73226990, 73226991, 73226992, 73226993, 73226994, 73226995, 73226996, 73226997, 73226998, 73226999, 73227000, 73227001, 73227002, 73227003, 73227004, 73227005, 73227006, 73227007, 73227008, 73227009, 73227010, 73227011, 73227012, 73227013, 73227014, 73227015, 73227016, 73227017, 73227018, 73227019, 73227020, 73227021, 73227022, 73227023, 73227024, 73227025, 73227026, 73227027, 73227028, 73227029, 73227030, 73227031, 73227032, 73227033, 73227034, 73227035, 73227036, 73227037, 73227038, 73227039, 73227040, 73227041, 73227042, 73227043, 73227044, 73227045, 73227046, 73227047, 73227048, 73227049, 73227050, 73227051, 73227052, 73227053, 73227054, 73227055, 73227056, 73227057, 73227058, 73227059, 73227060, 73227061, 73227062, 73227063, 73227064, 73227065, 73227066, 73227067, 73227068, 73227069, 73227070, 73227071, 73227072, 73227073, 73227074, 73227075, 73227076, 73227077, 73227078, 73227079, 73227080, 73227081, 73227082, 73227083, 73227084,

side note: due to HH:MM precision, the arrival_time (and thus trip_time and end_time columns) can only represent exact minutes, e.g. a value of 0 (which we will clean) actually means any amount of seconds between 0s and less than 60s (e.g. 30s becomes 0s), and 60s means any time between 60s and less than 120s (e.g. 100s becomes 60s)

In [32]:
# impute values with trip times <= 0 with 30s (reasonable approximation since it is only a few seconds between stops likely)
stop_total_times['trip_time'] = stop_total_times['trip_time'].clip(lower=0).replace(0, 30)

# recheck entries
invalid_trip_times = stop_total_times['trip_time'] <= 0
print("Trips with invalid trip_time:", stop_total_times[invalid_trip_times]['trip_id'].unique().tolist())

Trips with invalid trip_time: []

Group each trip by `from_stop` (Stop A) and `to_stop` (Stop B) and calculate the average travel time for each and every trip going from Stop A to Stop B

In [33]:
edge_list = stop_total_times.groupby(['from_stop', 'to_stop']).agg(
    number_of_trips=('trip_time', 'count'),
    average_trip_time=('trip_time', 'mean')
).reset_index()

edge_list

      from_stop  to_stop  number_of_trips  average_trip_time
0          1800     2788              646         178.142415
1          1802     5268              477          60.000000
2          1803     7747              229         120.000000
3          1804     1805             1112          60.000000
4          1805     1806             1112          47.077338
...         ...      ...              ...                ...
7567       9995     4000                1          60.000000
7568       9995     5478                1          60.000000
7569       9996     4977              858         138.531469
7570       9998     4548                2          30.000000
7571     112112     5709                2        1800.000000

[7572 rows x 4 columns]

In [34]:
# export edge list as data 
edge_list.to_csv('data/edge_list.csv', index=False)

---

Move all cleaned data into PostgreSQL database

In [35]:
# connect engine to PostgreSQL database
from sqlalchemy import create_engine
import os
from dotenv import load_dotenv

load_dotenv()
url = os.getenv("POSTGRES_URL")
engine = create_engine(url)

---