In [3]:
# run libraries
import pandas as pd
import numpy as np

In [29]:
# read and load data files
stops = pd.read_csv("data/stops.txt")
routes = pd.read_csv("data/routes.txt")
stop_times = pd.read_csv("data/stop_times.txt")
trips = pd.read_csv("data/trips.txt")
calendar = pd.read_csv("data/calendar.txt")
calendar_dates = pd.read_csv("data/calendar_dates.txt")
shapes = pd.read_csv("data/shapes.txt")

In [ ]:
# helper function to read schema for each dataframe
def schema(dataframe):
    print(dataframe.shape, "\n\nData Types:")
    print(dataframe.dtypes, "\n\nMissing Entries:")
    print(dataframe.isnull().sum())

---

## Stops

Description of what stops tells us

In [37]:
schema(stops)
stops.head()

(6173, 9)

Data Types:
stop_id            int64
stop_code          int64
stop_name         object
stop_desc        float64
stop_lat         float64
stop_lon         float64
zone_id          float64
stop_url         float64
location_type      int64
dtype: object

Missing Entries:
stop_id             0
stop_code           0
stop_name           0
stop_desc        6173
stop_lat            0
stop_lon            0
zone_id          6173
stop_url         6173
location_type       0
dtype: int64

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type
0,112112,112112,Crescent Heights High School,NaN,51.060931,-114.065158,NaN,NaN,0
1,1800,1800,EB 17 AV SE @ 84 ST SE,NaN,51.037651,-113.911093,NaN,NaN,0
2,1802,1802,NB Centre ST N @ 78 AV N nearside,NaN,51.122337,-114.071250,NaN,NaN,0
3,1803,1803,EB 46 AV SE @ Highfield CI SE,NaN,51.011541,-114.044189,NaN,NaN,0
4,1804,1804,EB 120 AV NE @ 16 ST NE,NaN,51.161538,-114.022383,NaN,NaN,0

In [25]:
# data cleaning

description of tasks and data cleaning and analysis/validation

---
## Routes

Description of what routes tells us

In [40]:
schema(routes)
routes.head()

(414, 8)

Data Types:
route_id             object
route_short_name     object
route_long_name      object
route_desc          float64
route_type            int64
route_url           float64
route_color         float64
route_text_color    float64
dtype: object

Missing Entries:
route_id              0
route_short_name      0
route_long_name       0
route_desc          414
route_type            0
route_url           414
route_color         414
route_text_color    414
dtype: int64

,route_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color
0,1-20781,1,Bowness/Forest Lawn,NaN,3,NaN,NaN,NaN
1,1-20789,1,Bowness/Forest Lawn,NaN,3,NaN,NaN,NaN
2,2-20781,2,Mount Pleasant/Killarney 17 Av SW,NaN,3,NaN,NaN,NaN
3,2-20789,2,Mount Pleasant/Killarney 17 Av SW,NaN,3,NaN,NaN,NaN
4,3-20781,3,Sandstone/Elbow Dr SW,NaN,3,NaN,NaN,NaN

In [ ]:
# data cleaning

description of tasks and data cleaning and analysis/validation

---

## Stop Times

description of stop times

In [45]:
schema(stop_times)
stop_times.head()

(3699315, 9)

Data Types:
trip_id                  int64
arrival_time            object
departure_time          object
stop_id                  int64
stop_sequence            int64
pickup_type              int64
drop_off_type            int64
shape_dist_traveled    float64
timepoint                int64
dtype: object

Missing Entries:
trip_id                0
arrival_time           0
departure_time         0
stop_id                0
stop_sequence          0
pickup_type            0
drop_off_type          0
shape_dist_traveled    0
timepoint              0
dtype: int64

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,shape_dist_traveled,timepoint
0,74468238,11:52:00,11:52:00,6451,1,0,0,0.000,1
1,74468238,11:53:00,11:53:00,6712,2,0,0,0.557,0
2,74468238,11:53:00,11:53:00,7276,3,0,0,0.866,0
3,74468238,11:59:00,11:59:00,8058,4,0,0,5.359,1
4,74468238,12:00:00,12:00:00,6338,5,0,0,5.659,0

---
## Trips

Description of what trips tells us

In [43]:
schema(trips)
trips.head()

(111146, 7)

Data Types:
route_id         object
service_id       object
trip_id           int64
trip_headsign    object
direction_id      int64
block_id          int64
shape_id          int64
dtype: object

Missing Entries:
route_id         0
service_id       0
trip_id          0
trip_headsign    0
direction_id     0
block_id         0
shape_id         0
dtype: int64

,route_id,service_id,trip_id,trip_headsign,direction_id,block_id,shape_id
0,36-20789,2026JU-1BUSSA-Saturday-02,74468238,RIVERBEND,0,7144090,360037
1,36-20789,2026JU-1BUSSA-Saturday-02,74468239,RIVERBEND,0,7144090,360037
2,36-20789,2026JU-1BUSSA-Saturday-02,74468240,RIVERBEND,0,7144090,360037
3,36-20789,2026JU-1BUSSA-Saturday-02,74468241,RIVERBEND,0,7144090,360037
4,36-20789,2026JU-1BUSSA-Saturday-02,74468242,RIVERBEND,0,7144090,360037

In [ ]:
# data cleaning

description of tasks and data cleaning and analysis/validation

---

## Calendar

Description of what stops tells us

In [46]:
schema(calendar)
calendar.head()

(33, 10)

Data Types:
service_id    object
monday         int64
tuesday        int64
wednesday      int64
thursday       int64
friday         int64
saturday       int64
sunday         int64
start_date     int64
end_date       int64
dtype: object

Missing Entries:
service_id    0
monday        0
tuesday       0
wednesday     0
thursday      0
friday        0
saturday      0
sunday        0
start_date    0
end_date      0
dtype: int64

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,2026MA-1BUSWK-Weekday-03,1,1,1,1,1,0,0,20260603,20260619
1,2026MA-1BUSWK-Weekday-03-1111000,1,1,1,1,0,0,0,20260603,20260619
2,2026MA-1BUSWK-Weekday-03-0000100,0,0,0,0,1,0,0,20260603,20260619
3,2026MA-1BUSSA-Saturday-03,0,0,0,0,0,1,0,20260606,20260620
4,2026MA-1BUSSU-Sunday-03,0,0,0,0,0,0,1,20260607,20260621

In [ ]:
# data cleaning

description of tasks and data cleaning and analysis/validation
- update start_date and end_date

---

## Calendar Dates

In [47]:
schema(calendar_dates)
calendar_dates.head()

(31, 3)

Data Types:
service_id        object
date               int64
exception_type     int64
dtype: object

Missing Entries:
service_id        0
date              0
exception_type    0
dtype: int64

                 service_id      date  exception_type
0  2026JU-1BUSWK-Weekday-02  20260701               2
1  2026JU-1BUSWK-Weekday-02  20260702               2
2  2026JU-1BUSWK-Weekday-02  20260703               2
3  2026JU-1BUSWK-Weekday-02  20260706               2
4  2026JU-1BUSWK-Weekday-02  20260707               2

---

## Shape

In [48]:
schema(shapes)
shapes.head()

(384646, 5)

Data Types:
shape_id                 int64
shape_pt_lat           float64
shape_pt_lon           float64
shape_pt_sequence        int64
shape_dist_traveled    float64
dtype: object

Missing Entries:
shape_id               0
shape_pt_lat           0
shape_pt_lon           0
shape_pt_sequence      0
shape_dist_traveled    0
dtype: int64

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
0,10180,51.052002,-113.941285,10001,0.000
1,10180,51.052017,-113.941298,10002,0.002
2,10180,51.052050,-113.941350,10003,0.007
3,10180,51.052061,-113.941391,10004,0.010
4,10180,51.052065,-113.941431,10005,0.013